### ISSUE TITLE
Opinion on URL routing

### ISSUE THREAD

**Issue by arulbakr** [anderspitman/SirTunnel#14]
I'd like to know your opinion on implementing URL routing on top of tunnelling. This is my use case. I have a few IoT devices and each has a webserver installed on it. Now, I want to achieve remote access to the web dashboard and have the SSH access to it too by having a common DNS. 

For example, lets say www.example.com is the domain. I want to access the IoT device's dashboard by www.example.com/DeviceId/web and for SSH, www.example.com/DeviceId/ssh

As far as I know, ngrok has this option available but expensive. I'd like to know if above use case can be achieved using this code with necessary changes.

**Comment by anderspitman** [comment]
You would probably need some custom software to do this. The problem is that SSH has no concept of a URL (or even domain names, it's all just IP addresses). I think the easiest way to get close to what you want is by setting up a generic TCP tunnel over TLS, and then connecting SSH over that tunnel. You might be able to accomplish that by compiling Caddy with the [layer 4 module](https://caddyserver.com/docs/modules/layer4), or by using [boringproxy](https://boringproxy.io/) with the `tuntls` command. See https://github.com/boringproxy/boringproxy/issues/163 and https://github.com/boringproxy/boringproxy/issues/167.

Either way you're probably going to need to understand how all this works on a pretty deep level to get it working.

Have you looked into Tailscale at all? I know they offer pretty comprehensive SSH support and have a solid free plan.

**Comment by arulbakr** [comment]
Thanks for the input Anders! Just came to know about Tailscale and will try to explore if it suits my expectation.
