### ISSUE TITLE
Detect and use correct arch in install.sh

### ISSUE THREAD

**Issue by scaleoutsean** [anderspitman/SirTunnel#2]
Install script shouldn't deploy an x86 binary of Caddy to ARM devices (for example).

**Comment by anderspitman** [comment]
Hey @scaleoutsean, thanks for the input! The install script is really just a convenience tool for the most common setup and intended to be adapted depending on your platform. If you need an arm build it would probably be easier to manually modify it for your needs, rather than trying to bake every possible platform into the script.
